require 'rails_helper'

RSpec.describe User, type: :model do
  before do
    user_params = Hash.new
    user_params[:f_name] = FFaker::Name.f_name
    user_params[:l_name] = FFaker::Name.l_name
    user_params[:email] = FFaker::Internet.email
    user_params[:password] = FFaker::Lorem.words(2).join
    @user = User.create(user_params)
  end

  describe "#email" do
    it "to be generated by ffaker" do
      expect(@user.full_name).to include(@)
    end
  end

end
