# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095a5bd7bba972874a503e8c9dfb500a3f8b5b65dbaccad2786b05e27c42f2f3b171ea12db86e5b7c2392ee41b9d1764909ea4785231ac1bf9c2045f6b50d5bd

test:
  secret_key_base: 252ed0cfb3d93c4d3369b7de751ebb0890ef41ea440368ba30ebedc79225b1d0d2a6e4929a1126803b05d062509083efba93fcc1f76547cc41ac4ce31b636feb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
